import Head from "next/dist/next-server/lib/head"
import EditorTiny from "../components/EditorTiny"
import { useState } from "react"

function editor() {
    const [html, setHtml] = useState('');
    const styles = {
        container: {
            margin: '10px 20px'
        }
    }
    return (
        <div style={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <h2>HTML Editor</h2>
            <EditorTiny />

        </div>
    )
}

export default editor

